### ISSUE TITLE
Suggestion: SIGIR 2021 E-Commerce Workshop Data Challenge 

### ISSUE THREAD

**Issue by tszumowski** [sisinflab/elliot#9]
Hi! I just discovered this project from links in a discussion area from another project. Having a look through here, I appreciate your features in the area of splitting, unique metrics, and stats tests!

I learned the other day that the SIGIR 2021 Conference has an e-commerce workshop data challenge, called **In-session prediction for purchase intent and recommendations**. They just opened it up for participation.

https://sigir-ecom.github.io/data-task.html

After looking at elliot's input structure, it seems like it wouldn't be too far off to connect elliot to the data challenge to get some elliot benchmarks out. Though, I didn't dig into the available models enough to know how they map to in-session datasets. 

Unfortunately I am unable to give it a go due to other professional commitments. But I figured I'd share it here as well as an opportunity to grow awareness around elliot, in the event others are interested.

**Comment by scne** [comment]
Hi @tszumowski,
thanks for the suggestion. During the last months, we are very busy due to some bugs still affected the code. Now with the latest version of Elliot, these are fully managed.
If in the next future you would like to collaborate in this direction we'd are very interesting to approach this direction in out framework.
